version: '3.9'
services:
  api_express:
    container_name: api_express
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - DB_HOST=database
      - DB_PORT=27017
      - DB_NAME=taskmanager
      - DB_USER=task
      - DB_PASSWORD=123456
    depends_on:
      - database
      
  database:
    container_name: mongoDb
    image: mongo:7
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongodb:/var/lib/mongodb/data

volumes:
  mongodb:
    driver: local


